In [1]:
import numpy as np

In [5]:
np.random.seed(55)
a=np.random.randint(30,99,(7,8))
a

array([[56, 69, 59, 91, 85, 67, 63, 84],
       [65, 76, 91, 42, 54, 61, 81, 30],
       [85, 92, 73, 79, 78, 40, 90, 89],
       [89, 74, 82, 51, 92, 82, 88, 91],
       [63, 75, 54, 48, 85, 57, 92, 48],
       [92, 86, 72, 97, 88, 37, 48, 95],
       [49, 49, 32, 62, 65, 63, 89, 51]])

In [6]:
a[-1]

array([49, 49, 32, 62, 65, 63, 89, 51])

In [7]:
a.ndim

2

In [12]:
a[0]

array([56, 69, 59, 91, 85, 67, 63, 84])

In [13]:
a.ndim

2

In [14]:
b=np.random.randint(20,80,(8,9))
b

array([[40, 23, 27, 40, 33, 54, 36, 60, 39],
       [46, 34, 49, 20, 68, 62, 30, 67, 78],
       [77, 24, 46, 34, 26, 45, 26, 57, 71],
       [25, 69, 49, 43, 25, 63, 45, 55, 58],
       [70, 38, 58, 65, 52, 49, 76, 34, 37],
       [27, 38, 50, 61, 53, 68, 45, 21, 63],
       [30, 75, 69, 70, 33, 71, 79, 72, 22],
       [43, 44, 56, 55, 50, 70, 33, 34, 56]])

In [15]:
b.shape

(8, 9)

In [16]:
b.ndim

2

In [17]:
b[7]

array([43, 44, 56, 55, 50, 70, 33, 34, 56])

In [18]:
b[7,0]#indexing

43

In [22]:
array[row_start: row_end : row_step , col_start: col_end:col_step]

In [20]:
b[2:6]

array([[77, 24, 46, 34, 26, 45, 26, 57, 71],
       [25, 69, 49, 43, 25, 63, 45, 55, 58],
       [70, 38, 58, 65, 52, 49, 76, 34, 37],
       [27, 38, 50, 61, 53, 68, 45, 21, 63]])

In [22]:
b[2:6:1,1:7:2]

array([[24, 34, 45],
       [69, 43, 63],
       [38, 65, 49],
       [38, 61, 68]])

In [26]:
import pandas as pd

In [27]:
pd.Series()


Series([], dtype: object)

In [29]:
pd.DataFrame

pandas.core.frame.DataFrame

In [34]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [36]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [38]:
t.ndim

2

In [39]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [40]:
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [45]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [46]:
df.columns

Index(['name', 'sub'], dtype='object')

In [47]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int64

In [49]:
df['sub'].mean()

17.25

In [50]:
df['sub'].median()

8.0

In [51]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int64

In [52]:
df['sub'].var()


482.9166666666667

In [53]:
df['sub'].std()

21.975364995072702

In [54]:
df['sub'].min()

3

In [55]:
df['sub'].max()

50

In [56]:
df['sub'].quantile(0.25)

6.0

In [57]:
df['sub'].quantile(0.75)

19.25