In [91]:
import numpy as np

In [ ]:
arr1=np.array(s)
arr1

In [ ]:
arr1.shape

In [ ]:
arr1.size

In [ ]:
h=d.reshape(2,3)
h

In [ ]:
h.size

In [ ]:
h.ndim

In [ ]:
range(5,20)

In [10]:
list(range(3,13,3))


[3, 6, 9, 12]

In [25]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [29]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [31]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [33]:
range (2.5,5,0.5)

TypeError: 'float' object cannot be interpreted as an integer

### range only work on integer values

In [ ]:
np.arange(2.5,5,0.5)

In [45]:
range(5,50,5)

range(5, 50, 5)

In [49]:
for i in range (5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [61]:
i=[5,87,23,46,62,84,80,45,77,33,80]
i

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [68]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])


In [74]:
for i in j:
    print()

In [95]:
d=np.array([10, 40, 50, 30, 70])
d

array([10, 40, 50, 30, 70])

In [97]:
np.mean(d)

40.0

In [99]:
np.median(d)

40.0

In [101]:
np.var(d)

400.0

In [103]:
np.std(d)

20.0

In [105]:
np.max(d)

70

In [107]:
np.min(d)

10

In [111]:
np.quantile(d,0.25)

30.0

In [125]:
np.quantile(d,0.75)

50.0

In [129]:
r=np.random.rand(5,3)
r

array([[0.662539  , 0.84992091, 0.29910768],
       [0.82817454, 0.12718059, 0.48703095],
       [0.92772159, 0.65126415, 0.35048576],
       [0.82372731, 0.45482335, 0.94639862],
       [0.5407156 , 0.32425463, 0.94226269]])

In [131]:
r.shape

(5, 3)

In [133]:
r.size

15

In [135]:
r.ndim

2

In [137]:
np.random.rand(30,1)

array([[0.24720993],
       [0.80665753],
       [0.79821001],
       [0.05404671],
       [0.84527895],
       [0.24434275],
       [0.1496812 ],
       [0.06427973],
       [0.9600848 ],
       [0.09856161],
       [0.22078798],
       [0.2985068 ],
       [0.79479687],
       [0.79859636],
       [0.42226769],
       [0.50417442],
       [0.99131956],
       [0.73538249],
       [0.3476717 ],
       [0.27673907],
       [0.9466091 ],
       [0.45191809],
       [0.42244653],
       [0.87455812],
       [0.33317371],
       [0.11665128],
       [0.24749323],
       [0.03634466],
       [0.108843  ],
       [0.15510992]])

In [139]:
np.random.normal(10,2,(4,5))

array([[10.59524336, 11.19187055, 12.32915881,  9.86963662, 10.60683617],
       [ 7.43803711, 12.26161807, 10.05598007, 14.05795564, 10.86923291],
       [ 7.38959726, 10.80969405,  8.92096006, 10.25646776, 11.4058612 ],
       [ 7.96649243,  8.97478032, 12.92359367,  9.98008014, 11.87302041]])

In [141]:
np.random.normal(40,5)

48.36804938012483

In [143]:
np.random.normal(10,2,(7,4))

array([[ 8.27858809,  9.282735  ,  8.61874908, 11.46943217],
       [ 9.54963061, 11.44468153,  7.91299745, 13.05261614],
       [14.30669066, 10.86372598, 10.51870553, 11.17941743],
       [13.72313534, 14.53820708, 11.00953351,  8.94930727],
       [11.72132758,  7.6003708 , 10.01108078, 12.50322965],
       [10.67540485,  7.98104847,  6.14739792,  9.03303427],
       [ 9.12513653, 13.28119593, 12.58556896,  8.96797474]])

In [147]:
np.random.randint(35,86,20)

array([78, 68, 44, 52, 38, 75, 52, 46, 53, 44, 79, 40, 78, 55, 44, 44, 41,
       52, 84, 58])