In [91]:
import numpy as np

In [ ]:
arr1=np.array(s)
arr1

In [ ]:
arr1.shape

In [ ]:
arr1.size

In [ ]:
h=d.reshape(2,3)
h

In [ ]:
h.size

In [ ]:
h.ndim

In [ ]:
range(5,20)

In [10]:
list(range(3,13,3))


[3, 6, 9, 12]

In [25]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [29]:
tuple(range(5,500,100))

(5, 105, 205, 305, 405)

In [31]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [33]:
range (2.5,5,0.5)

TypeError: 'float' object cannot be interpreted as an integer

### range only work on integer values

In [ ]:
np.arange(2.5,5,0.5)

In [45]:
range(5,50,5)

range(5, 50, 5)

In [49]:
for i in range (5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [61]:
i=[5,87,23,46,62,84,80,45,77,33,80]
i

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [68]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])


In [74]:
for i in j:
    print()

In [95]:
d=np.array([10, 40, 50, 30, 70])
d

array([10, 40, 50, 30, 70])

In [97]:
np.mean(d)

40.0

In [99]:
np.median(d)

40.0

In [101]:
np.var(d)

400.0

In [103]:
np.std(d)

20.0

In [105]:
np.max(d)

70

In [107]:
np.min(d)

10

In [111]:
np.quantile(d,0.25)

30.0

In [125]:
np.quantile(d,0.75)

50.0

In [129]:
r=np.random.rand(5,3)
r

array([[0.662539  , 0.84992091, 0.29910768],
       [0.82817454, 0.12718059, 0.48703095],
       [0.92772159, 0.65126415, 0.35048576],
       [0.82372731, 0.45482335, 0.94639862],
       [0.5407156 , 0.32425463, 0.94226269]])

In [131]:
r.shape

(5, 3)

In [133]:
r.size

15

In [135]:
r.ndim

2

In [137]:
np.random.rand(30,1)

array([[0.24720993],
       [0.80665753],
       [0.79821001],
       [0.05404671],
       [0.84527895],
       [0.24434275],
       [0.1496812 ],
       [0.06427973],
       [0.9600848 ],
       [0.09856161],
       [0.22078798],
       [0.2985068 ],
       [0.79479687],
       [0.79859636],
       [0.42226769],
       [0.50417442],
       [0.99131956],
       [0.73538249],
       [0.3476717 ],
       [0.27673907],
       [0.9466091 ],
       [0.45191809],
       [0.42244653],
       [0.87455812],
       [0.33317371],
       [0.11665128],
       [0.24749323],
       [0.03634466],
       [0.108843  ],
       [0.15510992]])

In [139]:
np.random.normal(10,2,(4,5))

array([[10.59524336, 11.19187055, 12.32915881,  9.86963662, 10.60683617],
       [ 7.43803711, 12.26161807, 10.05598007, 14.05795564, 10.86923291],
       [ 7.38959726, 10.80969405,  8.92096006, 10.25646776, 11.4058612 ],
       [ 7.96649243,  8.97478032, 12.92359367,  9.98008014, 11.87302041]])

In [141]:
np.random.normal(40,5)

48.36804938012483

In [143]:
np.random.normal(10,2,(7,4))

array([[ 8.27858809,  9.282735  ,  8.61874908, 11.46943217],
       [ 9.54963061, 11.44468153,  7.91299745, 13.05261614],
       [14.30669066, 10.86372598, 10.51870553, 11.17941743],
       [13.72313534, 14.53820708, 11.00953351,  8.94930727],
       [11.72132758,  7.6003708 , 10.01108078, 12.50322965],
       [10.67540485,  7.98104847,  6.14739792,  9.03303427],
       [ 9.12513653, 13.28119593, 12.58556896,  8.96797474]])

In [147]:
np.random.randint(35,86,20)

array([78, 68, 44, 52, 38, 75, 52, 46, 53, 44, 79, 40, 78, 55, 44, 44, 41,
       52, 84, 58])

# 18/01/25 Day 8

In [8]:
import numpy as np

In [10]:
s=[19,19,19,20,18,19,18,20,20,20]
s

[19, 19, 19, 20, 18, 19, 18, 20, 20, 20]

In [14]:
np.random.randint(18,21,500)

array([19, 20, 18, 19, 19, 19, 19, 20, 20, 18, 18, 20, 18, 20, 19, 19, 19,
       18, 19, 20, 19, 19, 18, 20, 19, 20, 19, 18, 20, 19, 19, 18, 18, 20,
       18, 20, 18, 20, 19, 19, 18, 19, 19, 19, 18, 19, 19, 20, 18, 18, 19,
       20, 20, 18, 18, 19, 19, 18, 18, 20, 20, 19, 20, 20, 20, 20, 20, 19,
       20, 20, 18, 18, 20, 19, 19, 20, 20, 18, 18, 18, 18, 19, 20, 19, 19,
       18, 18, 19, 20, 20, 20, 20, 19, 18, 19, 19, 20, 19, 19, 19, 20, 18,
       20, 19, 18, 18, 20, 18, 19, 18, 20, 20, 18, 20, 18, 19, 19, 20, 19,
       20, 20, 18, 20, 19, 19, 18, 20, 20, 20, 20, 19, 19, 19, 20, 18, 19,
       19, 18, 18, 20, 19, 19, 18, 19, 18, 18, 20, 20, 18, 18, 20, 18, 20,
       18, 18, 19, 19, 18, 20, 19, 20, 20, 20, 18, 20, 19, 18, 19, 18, 19,
       20, 19, 18, 20, 19, 19, 18, 18, 18, 19, 19, 18, 18, 19, 18, 18, 19,
       19, 20, 19, 20, 19, 18, 18, 20, 19, 19, 18, 20, 19, 19, 19, 18, 20,
       20, 19, 20, 20, 18, 20, 19, 19, 19, 19, 18, 18, 19, 18, 20, 20, 20,
       18, 19, 18, 19, 18

In [18]:
np.random.normal(35,10,1000)

array([35.08382289, 49.961432  , 15.78161601, 39.02165465, 35.80700225,
       21.60440609, 41.26285012, 24.23841037, 45.2498784 , 34.809227  ,
       35.13577219, 29.50532373, 24.62335314, 28.79528083, 14.32164053,
       54.52695191, 22.56230549, 32.55791422, 18.6273344 , 35.19736014,
       34.65747398, 41.97255742, 34.46992157, 22.21607034, 36.69976429,
       26.40713278, 32.97906916, 13.65345868, 29.83108379, 48.00765159,
       29.34302949, 27.14327942, 37.46362134, 48.64296976, 44.89191842,
       27.60955723, 44.3559844 , 37.80610758, 29.89921074, 31.43872727,
       34.53086641, 19.83254718, 29.494256  , 48.22437822, 21.94827978,
       45.46335338, 24.84148912, 33.91091424, 33.87862344, 29.48575371,
       36.6934391 , 52.08145431, 37.02530784, 32.69770864, 41.62545673,
       42.40534143, 30.01334302, 34.65766189, 40.52405148, 43.45088841,
       36.27335371, 58.3104637 , 42.48104188, 25.39748381, 38.97283562,
       18.62611925, 22.73963011, 46.68307078, 34.87405394, 44.30

In [24]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [28]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [30]:
tuple(x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [32]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [34]:
s

(36, 4, 9, 81, 49, 25, 64)

In [43]:
m=[]
for i in s:
    if i>30:
        m.append(i)

In [46]:
m

[36, 81, 49, 64]

In [53]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [55]:
arr+5

array([ 25,  55,  35,  75,  85,  45,  41,  59,  28, 103])

In [57]:
arr*100

array([2000, 5000, 3000, 7000, 8000, 4000, 3600, 5400, 2300, 9800])

In [59]:
arr/2

array([10. , 25. , 15. , 35. , 40. , 20. , 18. , 27. , 11.5, 49. ])

In [61]:
arr**2

array([ 400, 2500,  900, 4900, 6400, 1600, 1296, 2916,  529, 9604])

In [63]:
arr>30

array([False,  True, False,  True,  True,  True,  True,  True, False,
        True])

In [69]:
arr[arr>50]
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])