In [ ]:
import numpy as np

In [ ]:
np.random.seed(55)
a=np.random.randint(30,99,(7,8))
a

array([[56, 69, 59, 91, 85, 67, 63, 84],
       [65, 76, 91, 42, 54, 61, 81, 30],
       [85, 92, 73, 79, 78, 40, 90, 89],
       [89, 74, 82, 51, 92, 82, 88, 91],
       [63, 75, 54, 48, 85, 57, 92, 48],
       [92, 86, 72, 97, 88, 37, 48, 95],
       [49, 49, 32, 62, 65, 63, 89, 51]])

In [ ]:
a[-1]

array([49, 49, 32, 62, 65, 63, 89, 51])

In [ ]:
a.ndim

2

In [ ]:
a[0]

array([56, 69, 59, 91, 85, 67, 63, 84])

In [ ]:
a.ndim

2

In [ ]:
b=np.random.randint(20,80,(8,9))
b

array([[40, 23, 27, 40, 33, 54, 36, 60, 39],
       [46, 34, 49, 20, 68, 62, 30, 67, 78],
       [77, 24, 46, 34, 26, 45, 26, 57, 71],
       [25, 69, 49, 43, 25, 63, 45, 55, 58],
       [70, 38, 58, 65, 52, 49, 76, 34, 37],
       [27, 38, 50, 61, 53, 68, 45, 21, 63],
       [30, 75, 69, 70, 33, 71, 79, 72, 22],
       [43, 44, 56, 55, 50, 70, 33, 34, 56]])

In [ ]:
b.shape

(8, 9)

In [ ]:
b.ndim

2

In [ ]:
b[7]

array([43, 44, 56, 55, 50, 70, 33, 34, 56])

In [ ]:
b[7,0]#indexing

43

In [ ]:
array[row_start: row_end : row_step , col_start: col_end:col_step]

In [ ]:
b[2:6]

array([[77, 24, 46, 34, 26, 45, 26, 57, 71],
       [25, 69, 49, 43, 25, 63, 45, 55, 58],
       [70, 38, 58, 65, 52, 49, 76, 34, 37],
       [27, 38, 50, 61, 53, 68, 45, 21, 63]])

In [ ]:
b[2:6:1,1:7:2]

array([[24, 34, 45],
       [69, 43, 63],
       [38, 65, 49],
       [38, 61, 68]])

In [ ]:
import pandas as pd

In [ ]:
pd.Series()


Series([], dtype: object)

In [ ]:
pd.DataFrame

pandas.core.frame.DataFrame

In [ ]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [ ]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [ ]:
t.ndim

2

In [ ]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [ ]:
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [ ]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [ ]:
df.columns

Index(['name', 'sub'], dtype='object')

In [ ]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int64

In [ ]:
df['sub'].mean()

17.25

In [ ]:
df['sub'].median()

8.0

In [ ]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int64

In [ ]:
df['sub'].var()


482.9166666666667

In [ ]:
df['sub'].std()

21.975364995072702

In [ ]:
df['sub'].min()

3

In [ ]:
df['sub'].max()

50

In [ ]:
df['sub'].quantile(0.25)

6.0

In [ ]:
df['sub'].quantile(0.75)

19.25

In [ ]:
21/01/2025


In [1]:
import pandas as pd
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
sns.load_dataset('iris')

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
df=sns.load_dataset('taxis')
df

pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.shape

(6433, 14)

In [10]:
df.columns

Index(['pickup', 'dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls',
       'total', 'color', 'payment', 'pickup_zone', 'dropoff_zone',
       'pickup_borough', 'dropoff_borough'],
      dtype='object')

In [11]:
df['color']

0       yellow
1       yellow
2       yellow
3       yellow
4       yellow
         ...  
6428     green
6429     green
6430     green
6431     green
6432     green
Name: color, Length: 6433, dtype: object

In [12]:
df['color'].unique()

array(['yellow', 'green'], dtype=object)

In [13]:
df['color'].value_counts()

color
yellow    5451
green      982
Name: count, dtype: int64

In [14]:
df['payment'].unique()

array(['credit card', 'cash', nan], dtype=object)

In [15]:
df['payment'].value_counts()

payment
credit card    4577
cash           1812
Name: count, dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64         
 3   distance         6433 non-null   float64       
 4   fare             6433 non-null   float64       
 5   tip              6433 non-null   float64       
 6   tolls            6433 non-null   float64       
 7   total            6433 non-null   float64       
 8   color            6433 non-null   object        
 9   payment          6389 non-null   object        
 10  pickup_zone      6407 non-null   object        
 11  dropoff_zone     6388 non-null   object        
 12  pickup_borough   6407 non-null   object        
 13  dropoff_borough  6388 non-null   object        
dtypes: datetime64[ns](2), float64(5), int64(

In [25]:
 80 preprossing  10 tracing 10 fine tunning

SyntaxError: invalid syntax (<ipython-input-25-7d8c53cceee0>, line 1)

In [22]:
a=pd.Series(['India',5,2,8.6,4,9])
a

0    India
1        5
2        2
3      8.6
4        4
5        9
dtype: object

In [27]:
df[2]

KeyError: 2

In [28]:
df.iloc[2]


pickup             2019-03-27 17:53:01
dropoff            2019-03-27 18:00:25
passengers                           1
distance                          1.37
fare                               7.5
tip                               2.36
tolls                              0.0
total                            14.16
color                           yellow
payment                    credit card
pickup_zone              Alphabet City
dropoff_zone              West Village
pickup_borough               Manhattan
dropoff_borough              Manhattan
Name: 2, dtype: object

In [30]:
df.iloc[2:10]

pickup             dropoff  passengers  distance  fare   tip  \
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36   
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15   
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10   
5 2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49   7.5  2.16   
6 2019-03-26 21:07:31 2019-03-26 21:17:29           1      3.65  13.0  2.00   
7 2019-03-22 12:47:13 2019-03-22 12:58:17           0      1.40   8.5  0.00   
8 2019-03-23 11:48:50 2019-03-23 12:06:14           1      3.63  15.0  1.00   
9 2019-03-08 16:18:37 2019-03-08 16:26:57           1      1.52   8.0  1.00   

   tolls  total   color      payment                pickup_zone  \
2    0.0  14.16  yellow  credit card              Alphabet City   
3    0.0  36.95  yellow  credit card                  Hudson Sq   
4    0.0  13.40  yellow  credit card               Midtown East   
5    0.0  12.96  yellow  credit card  Times Sq/Theatre District   
6    0.0  18.80  yellow  credit card          Battery Park City   
7    0.0  11.80  yellow          NaN                Murray Hill   
8    0.0  19.30  yellow  credit card          East Harlem South   
9    0.0  13.30  yellow  credit card        Lincoln Square East   

              dropoff_zone pickup_borough dropoff_borough  
2             West Village      Manhattan       Manhattan  
3           Yorkville West      Manhattan       Manhattan  
4           Yorkville West      Manhattan       Manhattan  
5             Midtown East      Manhattan       Manhattan  
6  Two Bridges/Seward Park      Manhattan       Manhattan  
7                 Flatiron      Manhattan       Manhattan  
8           Midtown Center      Manhattan       Manhattan  
9             Central Park      Manhattan       Manhattan

In [31]:
df.iloc[2:10,3:10]

distance  fare   tip  tolls  total   color      payment
2      1.37   7.5  2.36    0.0  14.16  yellow  credit card
3      7.70  27.0  6.15    0.0  36.95  yellow  credit card
4      2.16   9.0  1.10    0.0  13.40  yellow  credit card
5      0.49   7.5  2.16    0.0  12.96  yellow  credit card
6      3.65  13.0  2.00    0.0  18.80  yellow  credit card
7      1.40   8.5  0.00    0.0  11.80  yellow          NaN
8      3.63  15.0  1.00    0.0  19.30  yellow  credit card
9      1.52   8.0  1.00    0.0  13.30  yellow  credit card

In [34]:
df.iloc[2:10,['distance','total','payment']]

IndexError: .iloc requires numeric indexers, got ['distance' 'total' 'payment']

In [35]:
a=np.random.randint(10,50,25)
a

array([44, 12, 18, 38, 49, 46, 40, 39, 28, 45, 12, 35, 18, 29, 42, 18, 16,
       46, 25, 14, 36, 32, 45, 19, 22])

In [36]:
a[a>30]

array([44, 38, 49, 46, 40, 39, 45, 35, 42, 46, 36, 32, 45])

In [37]:
df[df['payment']=='cash']

pickup             dropoff  passengers  distance  fare  tip  \
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.0   
10   2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0  0.0   
13   2019-03-19 07:55:25 2019-03-19 08:09:17           1      1.75  10.5  0.0   
14   2019-03-27 12:13:34 2019-03-27 12:25:48           0      2.90  11.5  0.0   
15   2019-03-16 17:53:34 2019-03-16 18:13:57           3      2.09  13.5  0.0   
...                  ...                 ...         ...       ...   ...  ...   
6420 2019-03-16 15:39:23 2019-03-16 15:46:18           2      1.20   7.0  0.0   
6422 2019-03-22 20:17:35 2019-03-22 20:36:07           1      4.02  16.0  0.0   
6424 2019-03-30 20:52:15 2019-03-30 20:59:55           1      1.70   8.0  0.0   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.0  0.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0  0.0   

      tolls  total   color payment               pickup_zone  \
1       0.0    9.3  yellow    cash     Upper West Side South   
10      0.0   17.8  yellow    cash         LaGuardia Airport   
13      0.0   13.8  yellow    cash       Lincoln Square West   
14      0.0   14.8  yellow    cash  Financial District North   
15      0.0   16.8  yellow    cash     Upper West Side North   
...     ...    ...     ...     ...                       ...   
6420    0.0    7.8   green    cash            Central Harlem   
6422    0.0   17.3   green    cash  Washington Heights South   
6424    0.0    9.3   green    cash            Central Harlem   
6427    0.0   20.0   green    cash               Parkchester   
6430    0.0   17.3   green    cash       Crown Heights North   

                    dropoff_zone pickup_borough dropoff_borough  
1          Upper West Side South      Manhattan       Manhattan  
10                       Astoria         Queens          Queens  
13     Times Sq/Theatre District      Manhattan       Manhattan  
14       Two Bridges/Seward Park      Manhattan       Manhattan  
15                  Clinton East      Manhattan       Manhattan  
...                          ...            ...             ...  
6420       Upper West Side North      Manhattan       Manhattan  
6422  Spuyten Duyvil/Kingsbridge      Manhattan           Bronx  
6424        Central Harlem North      Manhattan       Manhattan  
6427           East Harlem South          Bronx       Manhattan  
6430              Bushwick North       Brooklyn        Brooklyn  

[1812 rows x 14 columns]

In [40]:
df[df['total']>=10]

pickup             dropoff  passengers  distance   fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.00   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.50   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.00   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.00   
5    2019-03-11 10:37:23 2019-03-11 10:47:31           1      0.49   7.50   
...                  ...                 ...         ...       ...    ...   
6425 2019-03-07 15:34:30 2019-03-07 16:31:06           1      9.12  26.32   
6427 2019-03-23 18:26:09 2019-03-23 18:49:12           1      7.07  20.00   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.00   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.00   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.00   

       tip  tolls  total   color      payment                pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card            Lenox Hill West   
2     2.36    0.0  14.16  yellow  credit card              Alphabet City   
3     6.15    0.0  36.95  yellow  credit card                  Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card               Midtown East   
5     2.16    0.0  12.96  yellow  credit card  Times Sq/Theatre District   
...    ...    ...    ...     ...          ...                        ...   
6425  0.00    0.0  26.82   green  credit card                 Park Slope   
6427  0.00    0.0  20.00   green         cash                Parkchester   
6429  0.00    0.0  58.80   green  credit card                    Jamaica   
6430  0.00    0.0  17.30   green         cash        Crown Heights North   
6432  3.36    0.0  20.16   green  credit card                Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
5                         Midtown East      Manhattan       Manhattan  
...                                ...            ...             ...  
6425                     East New York       Brooklyn        Brooklyn  
6427                 East Harlem South          Bronx       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[5190 rows x 14 columns]